In [30]:
import pandas as pd
import numpy as np
import json

file_path = '/home/mantovani/Documents/IC/HMC_TE-s/Temp_Data/Dados_Dominios_Conservados/sequences.json'

df = {'Name':                   [],
      'Nucleotide_Sequence':    []}

with open(file_path, mode='r') as file:

    dados = json.load(file)

    for i in dados['results']:

        df['Name'].append(i['crossReferences'][0]['name'].strip()[0:11])
        df['Nucleotide_Sequence'].append(i['sequence'])
        
        l_reading_frames = len(i['openReadingFrames'])

        for j in range(l_reading_frames):

            reading_frame = i['openReadingFrames'][j]

            if f'Start_{j}' not in df:

                df[f'Start_{j}'] = []
                df[f'End_{j}'] = []
                df[f'Strand_{j}'] = []
                df[f'Protein_Sequence_{j}'] = []

            df[f'Start_{j}'].append(reading_frame['start'])
            df[f'End_{j}'].append(reading_frame['end'])
            df[f'Strand_{j}'].append(reading_frame['strand'])
            df[f'Protein_Sequence_{j}'].append(reading_frame['protein']['sequence'])

        for j in range(l_reading_frames, (len(df) - 1) // 4):  # Dividimos por 4 pois criamos 4 colunas por reading frame, subtraimos 1, pois desconsideramos o 'Name'

            df[f'Start_{j}'].append(np.nan)
            df[f'End_{j}'].append(np.nan)
            df[f'Strand_{j}'].append(np.nan)
            df[f'Protein_Sequence_{j}'].append(np.nan)

df = pd.DataFrame(df)
df.head()

Name                                Nucleotide_Sequence  Start_0  \
0  DF000000001  acagtatagcatagtggttaagagcacgggctctggagccagactg...       21   
1  DF000000006  tctatctatataaaatgcttaggtatgtttccccaaggttcagctg...      627   
2  DF000000004  cagtcatgcgccgcataacgacgtttcggtcaacgacggaccgcat...      251   
3  DF000000008  atggtagatttaaacccaancatatcaataattacattaaatgtaa...      543   
4  DF000000007  ggccgggcgcggtggctcacgcctgtaatcccagcactttgggagg...      229   

   End_0   Strand_0                                 Protein_Sequence_0  \
0    119  ANTISENSE                  GTERLSNLPKVTQLVSGRAGIRTQAVWLQSPCS   
1    788  ANTISENSE  TYRKLSSFEYERHICIRWNERYARYENSIQVHCSAHSCNTYFLCYA...   
2    331      SENSE                        VCVSTLYDVRTTTKSPNDAFLRTYPRR   
3    851  ANTISENSE  YVVFSXSFSSKYFLISXVISSLTHGLFRSVLFNFQIFGDFLXIFLL...   
4    312      SENSE                       AVIAPLHSSLGDRARPCLKKKKKKKKKK   

   Start_1  End_1   Strand_1  \
0       22    135      SENSE   
1      373    672  ANTISENSE   
2      108    221  ANTISENSE   
3        3    311  ANTISENSE   
4        3    311  ANTISENSE   

                                  Protein_Sequence_1  ...   Strand_5  \
0             EHGLWSQTAWVRIPALPLTSCVTLGKLLNLSVPQFPHL  ...      SENSE   
1  HIFPMLCSSTVDYSLLIIRIRYFYLISPRRFALFLLISNRSSLSSM...  ...      SENSE   
2             AIWYSLLLLGYKPVQHVTVLNTVGNCNTMVSICVSKHI  ...  ANTISENSE   
3  IDPFIIMKCPSLSLVIFLALKSTLSDINIATPAFFXLVFAWYIFFH...  ...  ANTISENSE   
4  FFFFFFFFFLRQGLALSPRLECSGAITAHCSLDLPGSSDPPASASR...  ...  ANTISENSE   

                                  Protein_Sequence_5 Start_6 End_6   Strand_6  \
0                       QYSIVVKSTGSGARLPGFESRLCHLLAV     167   250  ANTISENSE   
1  AFIYLIKGLKVLRSVKMAEPCVRTLRNRRRNANETLEERSNRLRDR...     175   336      SENSE   
2  VMRRLTTGIRSEKCVVRRFRRCANIIECTYTNLDGIAYYTPRLYGI...       2   115      SENSE   
3  XVEHLFMCLLAIXISSFVKCLFKSFAHFXIGLFVFXLLXCRSSLYI...    2617  2898  ANTISENSE   
4  FFFFFFFFFFETGSRSVAQAGVQWRDHGSLQPRPPGLKRSSRLSLP...     204   311      SENSE   

                                  Protein_Sequence_6 Start_7 End_7   Strand_7  \
0                       HLLSAYYVPGTVLSALHVLTHLILTTTL     181   261      SENSE   
1  ELYAFLSIYLLNLFEIXLRISTTCNVKHVSPILNLIQCIKVFIRIV...     641   871  ANTISENSE   
2             SHAPHNDVSVNDGPHIRRWSHKIIIPYFYCTFSMFRYV      75   194      SENSE   
3  VYDPSXINFCVWCEVGVEXHFFPYGYPIVPAPFVEKTILSPLNCXG...    1902  2351  ANTISENSE   
4               AREVEAAVSRDRATALQPGRQSETLSQKKKKKKKKK       1   225      SENSE   

                                  Protein_Sequence_7  
0                        GLNELIHVKRLEQCLAHSKRSINVSYY  
1  LNTGFGRYKQILSKVCPCDLLMVIEKAKRIGNCLLLNMKGIFVSDG...  
2           YRIFTVPFLCLDMFRYTNTYHCVTIAYSIQYSNMLYRFVA  
3  FSVXRSCTXFVRFIPKYXMFFDAIVNGIVFXISFSNCLLLVYRNTI...  
4  GRARWLTPVIPALWEAEAGGSLEPRSSRPAWATWRNPVSTKNTKIS...  

[5 rows x 34 columns]

In [27]:
Aminoacido_Nucleotidio = {
    'F': ('UUU', 'UUC'),
    'L': ('UUA', 'UUG', 'CUU', 'CUC', 'CUA', 'CUG'),
    'I': ('AUU', 'AUC', 'AUA'),
    'M': ('AUG'),
    'V': ('GUU', 'GUC', 'GUA', 'GUG'),
    'S': ('UCU', 'UCC', 'UCA', 'UCG', 'AGU', 'AGC'),
    'P': ('CCU', 'CCC', 'CCA', 'CCG'),
    'T': ('ACU', 'ACC', 'ACA', 'ACG'),
    'A': ('GCU', 'GCC', 'GCA', 'GCG'),
    'Y': ('UAU', 'UAC'),
    'H': ('CAU', 'CAC'),
    'Q': ('CAA', 'CAG'),
    'N': ('AAU', 'AAC'),
    'K': ('AAA', 'AAG'),
    'D': ('GAU', 'GAC'),
    'E': ('GAA', 'GAG'),
    'C': ('UGU', 'UGC'),
    'W': ('UGG'),
    'R': ('CGU', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG'),
    'G': ('GGU', 'GGC', 'GGA', 'GGG'),
    '*': ('UAA', 'UAG', 'UGA')  # Códons de parada
}

def grafo_N(nulceotidio: str) -> list:

    nulceotidio:str = nulceotidio.upper()

    if nulceotidio == 'A':

        return [1,0,0,0,0]
    
    elif nulceotidio == 'C':

        return [0,1,0,0,0]
    
    elif nulceotidio == 'G':

        return [0,0,1,0,0]
    
    elif nulceotidio == 'U':

        return [0,0,0,1,0]
    
    else: 

        return [0,0,0,0,1]
    

def Proteina_trinca(proteina: str) -> np.ndarray:

    def Aminoacido_Grafo(aminoacido: str) -> np.ndarray:

        A = [np.array([grafo_N(j) for j in i]) for i in Aminoacido_Nucleotidio.get(aminoacido, [])]
        
        codon_array = np.logical_or.reduce(A)

        return codon_array

    proteina = proteina.upper()

    B = [Aminoacido_Grafo(i) for i in proteina.strip()]

    return np.vstack(B).astype(int)

def Sequencia_grafo(sequencia: str) -> np.ndarray:

    a = [grafo_N(i) for i in sequencia.strip()]

    return np.array(a)

In [29]:
print('proteina: \n', Proteina_trinca('GTERLSNLPKVTQLVSGRAGIRTQAVWLQSPCS'))

print('\n', Sequencia_grafo("acagtatagcatagtggttaagagcacgggctctggagccagactgcctgggttcgaatcccggctctgccacttactagctgtgtgaccttgggcaagttacttaacctctctgtgcctcagtttcctcatctgtaaaatggggataataatagtacctacctcatagggttgttgtgaggattaaatgagttaatacatgtaaagcgcttagaacagtgcctggcacatagtaagcgctcaataaatgttagctattatt"))


 [[1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 ...
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]]


In [ ]:
def agrupar_tensor(linha: pd.DataFrame)